//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AG.Claims.Audatex.AudatexOutbound {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageHeaderType", Namespace="http://schemas.datacontract.org/2004/07/Audatex.B2B.DataModels.DuckCreek")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AG.Claims.Audatex.AudatexOutbound.AssignmentAddRs))]
    public partial class MessageHeaderType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string asyncRqUIDFieldField;
        
        private string partnerKeyFieldField;
        
        private string rqUIDFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string asyncRqUIDField {
            get {
                return this.asyncRqUIDFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.asyncRqUIDFieldField, value) != true)) {
                    this.asyncRqUIDFieldField = value;
                    this.RaisePropertyChanged("asyncRqUIDField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string partnerKeyField {
            get {
                return this.partnerKeyFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.partnerKeyFieldField, value) != true)) {
                    this.partnerKeyFieldField = value;
                    this.RaisePropertyChanged("partnerKeyField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string rqUIDField {
            get {
                return this.rqUIDFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.rqUIDFieldField, value) != true)) {
                    this.rqUIDFieldField = value;
                    this.RaisePropertyChanged("rqUIDField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssignmentAddRs", Namespace="http://schemas.datacontract.org/2004/07/Audatex.B2B.DataModels.DuckCreek")]
    [System.SerializableAttribute()]
    public partial class AssignmentAddRs : AG.Claims.Audatex.AudatexOutbound.MessageHeaderType {
        
        private AG.Claims.Audatex.AudatexOutbound.ApplicationStatusType applicationStatusFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AG.Claims.Audatex.AudatexOutbound.ApplicationStatusType applicationStatusField {
            get {
                return this.applicationStatusFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.applicationStatusFieldField, value) != true)) {
                    this.applicationStatusFieldField = value;
                    this.RaisePropertyChanged("applicationStatusField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationStatusType", Namespace="http://schemas.datacontract.org/2004/07/Audatex.B2B.DataModels.DuckCreek")]
    [System.SerializableAttribute()]
    public partial class ApplicationStatusType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private AG.Claims.Audatex.AudatexOutbound.ApplicationStatusTypeApplicationError[] applicationErrorFieldField;
        
        private AG.Claims.Audatex.AudatexOutbound.ApplicationStatusOpenEnumType applicationStatusCodeFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AG.Claims.Audatex.AudatexOutbound.ApplicationStatusTypeApplicationError[] applicationErrorField {
            get {
                return this.applicationErrorFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.applicationErrorFieldField, value) != true)) {
                    this.applicationErrorFieldField = value;
                    this.RaisePropertyChanged("applicationErrorField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AG.Claims.Audatex.AudatexOutbound.ApplicationStatusOpenEnumType applicationStatusCodeField {
            get {
                return this.applicationStatusCodeFieldField;
            }
            set {
                if ((this.applicationStatusCodeFieldField.Equals(value) != true)) {
                    this.applicationStatusCodeFieldField = value;
                    this.RaisePropertyChanged("applicationStatusCodeField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationStatusTypeApplicationError", Namespace="http://schemas.datacontract.org/2004/07/Audatex.B2B.DataModels.DuckCreek")]
    [System.SerializableAttribute()]
    public partial class ApplicationStatusTypeApplicationError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string errorCodeFieldField;
        
        private string errorDescFieldField;
        
        private string severityFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string errorCodeField {
            get {
                return this.errorCodeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.errorCodeFieldField, value) != true)) {
                    this.errorCodeFieldField = value;
                    this.RaisePropertyChanged("errorCodeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string errorDescField {
            get {
                return this.errorDescFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.errorDescFieldField, value) != true)) {
                    this.errorDescFieldField = value;
                    this.RaisePropertyChanged("errorDescField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string severityField {
            get {
                return this.severityFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.severityFieldField, value) != true)) {
                    this.severityFieldField = value;
                    this.RaisePropertyChanged("severityField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationStatusOpenEnumType", Namespace="http://schemas.datacontract.org/2004/07/Audatex.B2B.DataModels.DuckCreek")]
    public enum ApplicationStatusOpenEnumType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Accept = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Partial = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reject = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AudatexOutbound.IAudatexB2BFNOLService")]
    public interface IAudatexB2BFNOLService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudatexB2BFNOLService/AddFnol", ReplyAction="http://tempuri.org/IAudatexB2BFNOLService/AddFnolResponse")]
        AG.Claims.Audatex.AudatexOutbound.AssignmentAddRs AddFnol(string assignmentAddRq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudatexB2BFNOLService/AddFnol", ReplyAction="http://tempuri.org/IAudatexB2BFNOLService/AddFnolResponse")]
        System.Threading.Tasks.Task<AG.Claims.Audatex.AudatexOutbound.AssignmentAddRs> AddFnolAsync(string assignmentAddRq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAudatexB2BFNOLServiceChannel : AG.Claims.Audatex.AudatexOutbound.IAudatexB2BFNOLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AudatexB2BFNOLServiceClient : System.ServiceModel.ClientBase<AG.Claims.Audatex.AudatexOutbound.IAudatexB2BFNOLService>, AG.Claims.Audatex.AudatexOutbound.IAudatexB2BFNOLService {
        
        public AudatexB2BFNOLServiceClient() {
        }
        
        public AudatexB2BFNOLServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AudatexB2BFNOLServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AudatexB2BFNOLServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AudatexB2BFNOLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AG.Claims.Audatex.AudatexOutbound.AssignmentAddRs AddFnol(string assignmentAddRq) {
            return base.Channel.AddFnol(assignmentAddRq);
        }
        
        public System.Threading.Tasks.Task<AG.Claims.Audatex.AudatexOutbound.AssignmentAddRs> AddFnolAsync(string assignmentAddRq) {
            return base.Channel.AddFnolAsync(assignmentAddRq);
        }
    }
}
