//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AG.Claims.Audatex.AG_Audatex {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AG_Audatex.IAG_Audatex")]
    public interface IAG_Audatex {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAG_Audatex/UploadAudatexResponse", ReplyAction="http://tempuri.org/IAG_Audatex/UploadAudatexResponseResponse")]
        string UploadAudatexResponse(AG.Claims.Integration.Types.AG_AudatexInboundDTO audatexDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAG_Audatex/UploadAudatexResponse", ReplyAction="http://tempuri.org/IAG_Audatex/UploadAudatexResponseResponse")]
        System.Threading.Tasks.Task<string> UploadAudatexResponseAsync(AG.Claims.Integration.Types.AG_AudatexInboundDTO audatexDetails);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAG_AudatexChannel : AG.Claims.Audatex.AG_Audatex.IAG_Audatex, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AG_AudatexClient : System.ServiceModel.ClientBase<AG.Claims.Audatex.AG_Audatex.IAG_Audatex>, AG.Claims.Audatex.AG_Audatex.IAG_Audatex {
        
        public AG_AudatexClient() {
        }
        
        public AG_AudatexClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AG_AudatexClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AG_AudatexClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AG_AudatexClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UploadAudatexResponse(AG.Claims.Integration.Types.AG_AudatexInboundDTO audatexDetails) {
            return base.Channel.UploadAudatexResponse(audatexDetails);
        }
        
        public System.Threading.Tasks.Task<string> UploadAudatexResponseAsync(AG.Claims.Integration.Types.AG_AudatexInboundDTO audatexDetails) {
            return base.Channel.UploadAudatexResponseAsync(audatexDetails);
        }
    }
}
