//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AG.Claims.IVAuto
{


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PG_AssignmentInfo", Namespace="http://schemas.datacontract.org/2004/07/SGISalvageAppDataService.Assignment")]
    [System.SerializableAttribute()]
    public partial class PG_AssignmentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AG.Claims.IVAuto.PG_Enums_CoverageTypes CoverageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsuranceAdjusterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsuranceCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsuranceOfficeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AG.Claims.IVAuto.PG_Enums_LossCauseTypes LossCauseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LossDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AG.Claims.IVAuto.PG_OwnerInfo OwnerDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AG.Claims.IVAuto.PG_LocationInfo PickupLocationDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AG.Claims.IVAuto.PG_VehicleInfo VehicleDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimNumber {
            get {
                return this.ClaimNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimNumberField, value) != true)) {
                    this.ClaimNumberField = value;
                    this.RaisePropertyChanged("ClaimNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AG.Claims.IVAuto.PG_Enums_CoverageTypes CoverageType {
            get {
                return this.CoverageTypeField;
            }
            set {
                if ((this.CoverageTypeField.Equals(value) != true)) {
                    this.CoverageTypeField = value;
                    this.RaisePropertyChanged("CoverageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuranceAdjuster {
            get {
                return this.InsuranceAdjusterField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuranceAdjusterField, value) != true)) {
                    this.InsuranceAdjusterField = value;
                    this.RaisePropertyChanged("InsuranceAdjuster");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuranceCompany {
            get {
                return this.InsuranceCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuranceCompanyField, value) != true)) {
                    this.InsuranceCompanyField = value;
                    this.RaisePropertyChanged("InsuranceCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuranceOffice {
            get {
                return this.InsuranceOfficeField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuranceOfficeField, value) != true)) {
                    this.InsuranceOfficeField = value;
                    this.RaisePropertyChanged("InsuranceOffice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AG.Claims.IVAuto.PG_Enums_LossCauseTypes LossCause {
            get {
                return this.LossCauseField;
            }
            set {
                if ((this.LossCauseField.Equals(value) != true)) {
                    this.LossCauseField = value;
                    this.RaisePropertyChanged("LossCause");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LossDate {
            get {
                return this.LossDateField;
            }
            set {
                if ((this.LossDateField.Equals(value) != true)) {
                    this.LossDateField = value;
                    this.RaisePropertyChanged("LossDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AG.Claims.IVAuto.PG_OwnerInfo OwnerDetails {
            get {
                return this.OwnerDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerDetailsField, value) != true)) {
                    this.OwnerDetailsField = value;
                    this.RaisePropertyChanged("OwnerDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AG.Claims.IVAuto.PG_LocationInfo PickupLocationDetails {
            get {
                return this.PickupLocationDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.PickupLocationDetailsField, value) != true)) {
                    this.PickupLocationDetailsField = value;
                    this.RaisePropertyChanged("PickupLocationDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockNo {
            get {
                return this.StockNoField;
            }
            set {
                if ((this.StockNoField.Equals(value) != true)) {
                    this.StockNoField = value;
                    this.RaisePropertyChanged("StockNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AG.Claims.IVAuto.PG_VehicleInfo VehicleDetails {
            get {
                return this.VehicleDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleDetailsField, value) != true)) {
                    this.VehicleDetailsField = value;
                    this.RaisePropertyChanged("VehicleDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PG_OwnerInfo", Namespace="http://schemas.datacontract.org/2004/07/SGISalvageAppDataService.Assignment")]
    [System.SerializableAttribute()]
    public partial class PG_OwnerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomePhone {
            get {
                return this.HomePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.HomePhoneField, value) != true)) {
                    this.HomePhoneField = value;
                    this.RaisePropertyChanged("HomePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkPhone {
            get {
                return this.WorkPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkPhoneField, value) != true)) {
                    this.WorkPhoneField = value;
                    this.RaisePropertyChanged("WorkPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((this.ZipCodeField.Equals(value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PG_LocationInfo", Namespace="http://schemas.datacontract.org/2004/07/SGISalvageAppDataService.Assignment")]
    [System.SerializableAttribute()]
    public partial class PG_LocationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPerson {
            get {
                return this.ContactPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonField, value) != true)) {
                    this.ContactPersonField = value;
                    this.RaisePropertyChanged("ContactPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((this.ZipCodeField.Equals(value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PG_VehicleInfo", Namespace="http://schemas.datacontract.org/2004/07/SGISalvageAppDataService.Assignment")]
    [System.SerializableAttribute()]
    public partial class PG_VehicleInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make {
            get {
                return this.MakeField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeField, value) != true)) {
                    this.MakeField = value;
                    this.RaisePropertyChanged("Make");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VIN {
            get {
                return this.VINField;
            }
            set {
                if ((object.ReferenceEquals(this.VINField, value) != true)) {
                    this.VINField = value;
                    this.RaisePropertyChanged("VIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PG_Enums_CoverageTypes", Namespace="http://schemas.datacontract.org/2004/07/SGISalvageAppEnums")]
    public enum PG_Enums_CoverageTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        _NotSelected_ = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Comp = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Collision = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PG_Enums_LossCauseTypes", Namespace="http://schemas.datacontract.org/2004/07/SGISalvageAppEnums")]
    public enum PG_Enums_LossCauseTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        _NotSelected_ = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Collision = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fire = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Flood_Water = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hail = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RollOver = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stripped = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Theft_Repo = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Theft_Recovery = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Theft_Stripped = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unrecovered_Theft = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vandalism = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Water = 13,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PG_ResponseData", Namespace="http://schemas.datacontract.org/2004/07/SGISalvageAppDataService.Assignment")]
    [System.SerializableAttribute()]
    public partial class PG_ResponseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AG.Claims.IVAuto.PG_AssignmentDetailedInfo ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AG.Claims.IVAuto.PG_AssignmentDetailedInfo Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PG_AssignmentDetailedInfo", Namespace="http://schemas.datacontract.org/2004/07/SGISalvageAppDataService.Assignment")]
    [System.SerializableAttribute()]
    public partial class PG_AssignmentDetailedInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ActualPickupDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AdvanceChargesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ApprovedToMoveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AG.Claims.IVAuto.PG_AssignmentInfo AssignmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool KeysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PickupAssignedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReceivedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AG.Claims.IVAuto.PG_LocationInfo SalvageYardInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TitleReceivedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ActualPickupDate {
            get {
                return this.ActualPickupDateField;
            }
            set {
                if ((this.ActualPickupDateField.Equals(value) != true)) {
                    this.ActualPickupDateField = value;
                    this.RaisePropertyChanged("ActualPickupDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AdvanceCharges {
            get {
                return this.AdvanceChargesField;
            }
            set {
                if ((this.AdvanceChargesField.Equals(value) != true)) {
                    this.AdvanceChargesField = value;
                    this.RaisePropertyChanged("AdvanceCharges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ApprovedToMoveDate {
            get {
                return this.ApprovedToMoveDateField;
            }
            set {
                if ((this.ApprovedToMoveDateField.Equals(value) != true)) {
                    this.ApprovedToMoveDateField = value;
                    this.RaisePropertyChanged("ApprovedToMoveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AG.Claims.IVAuto.PG_AssignmentInfo Assignment {
            get {
                return this.AssignmentField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignmentField, value) != true)) {
                    this.AssignmentField = value;
                    this.RaisePropertyChanged("Assignment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Keys {
            get {
                return this.KeysField;
            }
            set {
                if ((this.KeysField.Equals(value) != true)) {
                    this.KeysField = value;
                    this.RaisePropertyChanged("Keys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PickupAssignedDate {
            get {
                return this.PickupAssignedDateField;
            }
            set {
                if ((this.PickupAssignedDateField.Equals(value) != true)) {
                    this.PickupAssignedDateField = value;
                    this.RaisePropertyChanged("PickupAssignedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReceivedDate {
            get {
                return this.ReceivedDateField;
            }
            set {
                if ((this.ReceivedDateField.Equals(value) != true)) {
                    this.ReceivedDateField = value;
                    this.RaisePropertyChanged("ReceivedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AG.Claims.IVAuto.PG_LocationInfo SalvageYardInfo {
            get {
                return this.SalvageYardInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SalvageYardInfoField, value) != true)) {
                    this.SalvageYardInfoField = value;
                    this.RaisePropertyChanged("SalvageYardInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TitleReceivedDate {
            get {
                return this.TitleReceivedDateField;
            }
            set {
                if ((this.TitleReceivedDateField.Equals(value) != true)) {
                    this.TitleReceivedDateField = value;
                    this.RaisePropertyChanged("TitleReceivedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PG_AdjusterInfo", Namespace="http://schemas.datacontract.org/2004/07/SGISalvageAppDataService.Assignment")]
    [System.SerializableAttribute()]
    public partial class PG_AdjusterInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdjusterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdjusterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AdjusterId {
            get {
                return this.AdjusterIdField;
            }
            set {
                if ((this.AdjusterIdField.Equals(value) != true)) {
                    this.AdjusterIdField = value;
                    this.RaisePropertyChanged("AdjusterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdjusterName {
            get {
                return this.AdjusterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AdjusterNameField, value) != true)) {
                    this.AdjusterNameField = value;
                    this.RaisePropertyChanged("AdjusterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IVService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/SaveAssignment", ReplyAction="http://tempuri.org/IDataService/SaveAssignmentResponse")]
        AG.Claims.IVAuto.PG_ResponseData SaveAssignment(AG.Claims.IVAuto.PG_AssignmentInfo assignment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/SaveAssignment", ReplyAction="http://tempuri.org/IDataService/SaveAssignmentResponse")]
        System.Threading.Tasks.Task<AG.Claims.IVAuto.PG_ResponseData> SaveAssignmentAsync(AG.Claims.IVAuto.PG_AssignmentInfo assignment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateAssignment", ReplyAction="http://tempuri.org/IDataService/UpdateAssignmentResponse")]
        AG.Claims.IVAuto.PG_ResponseData UpdateAssignment(AG.Claims.IVAuto.PG_AssignmentInfo assignmentUpdated);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateAssignment", ReplyAction="http://tempuri.org/IDataService/UpdateAssignmentResponse")]
        System.Threading.Tasks.Task<AG.Claims.IVAuto.PG_ResponseData> UpdateAssignmentAsync(AG.Claims.IVAuto.PG_AssignmentInfo assignmentUpdated);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAssignment", ReplyAction="http://tempuri.org/IDataService/GetAssignmentResponse")]
        AG.Claims.IVAuto.PG_ResponseData GetAssignment(int StockNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAssignment", ReplyAction="http://tempuri.org/IDataService/GetAssignmentResponse")]
        System.Threading.Tasks.Task<AG.Claims.IVAuto.PG_ResponseData> GetAssignmentAsync(int StockNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAdjustersForCalCas", ReplyAction="http://tempuri.org/IDataService/GetAdjustersForCalCasResponse")]
        System.Collections.Generic.List<AG.Claims.IVAuto.PG_AdjusterInfo> GetAdjustersForCalCas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAdjustersForCalCas", ReplyAction="http://tempuri.org/IDataService/GetAdjustersForCalCasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AG.Claims.IVAuto.PG_AdjusterInfo>> GetAdjustersForCalCasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : AG.Claims.IVAuto.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<AG.Claims.IVAuto.IDataService>, AG.Claims.IVAuto.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AG.Claims.IVAuto.PG_ResponseData SaveAssignment(AG.Claims.IVAuto.PG_AssignmentInfo assignment) {
            return base.Channel.SaveAssignment(assignment);
        }
        
        public System.Threading.Tasks.Task<AG.Claims.IVAuto.PG_ResponseData> SaveAssignmentAsync(AG.Claims.IVAuto.PG_AssignmentInfo assignment) {
            return base.Channel.SaveAssignmentAsync(assignment);
        }
        
        public AG.Claims.IVAuto.PG_ResponseData UpdateAssignment(AG.Claims.IVAuto.PG_AssignmentInfo assignmentUpdated) {
            return base.Channel.UpdateAssignment(assignmentUpdated);
        }
        
        public System.Threading.Tasks.Task<AG.Claims.IVAuto.PG_ResponseData> UpdateAssignmentAsync(AG.Claims.IVAuto.PG_AssignmentInfo assignmentUpdated) {
            return base.Channel.UpdateAssignmentAsync(assignmentUpdated);
        }
        
        public AG.Claims.IVAuto.PG_ResponseData GetAssignment(int StockNo) {
            return base.Channel.GetAssignment(StockNo);
        }
        
        public System.Threading.Tasks.Task<AG.Claims.IVAuto.PG_ResponseData> GetAssignmentAsync(int StockNo) {
            return base.Channel.GetAssignmentAsync(StockNo);
        }
        
        public System.Collections.Generic.List<AG.Claims.IVAuto.PG_AdjusterInfo> GetAdjustersForCalCas() {
            return base.Channel.GetAdjustersForCalCas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AG.Claims.IVAuto.PG_AdjusterInfo>> GetAdjustersForCalCasAsync() {
            return base.Channel.GetAdjustersForCalCasAsync();
        }
    }
}
