//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AG.Claims.LXNX.AG_CCR {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://decisioning.lexisnexis.com/ws/rules/orderhandler")]
    public partial class SOAPFaultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://decisioning.lexisnexis.com/ws/rules/orderhandler", ConfigurationName="AG_CCR.ohws")]
    public interface ohws {
        
        // CODEGEN: Parameter 'response' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AG.Claims.LXNX.AG_CCR.SOAPFaultInfo), Action="", Name="SecurityFailure")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        AG.Claims.LXNX.AG_CCR.PlaceInteractiveOrderResponse PlaceInteractiveOrder(AG.Claims.LXNX.AG_CCR.PlaceInteractiveOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AG.Claims.LXNX.AG_CCR.PlaceInteractiveOrderResponse> PlaceInteractiveOrderAsync(AG.Claims.LXNX.AG_CCR.PlaceInteractiveOrder request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PlaceInteractiveOrder", WrapperNamespace="http://decisioning.lexisnexis.com/ws/rules/orderhandler", IsWrapped=true)]
    public partial class PlaceInteractiveOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://decisioning.lexisnexis.com/ws/rules/orderhandler", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string request;
        
        public PlaceInteractiveOrder() {
        }
        
        public PlaceInteractiveOrder(string request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PlaceInteractiveOrderResponse", WrapperNamespace="http://decisioning.lexisnexis.com/ws/rules/orderhandler", IsWrapped=true)]
    public partial class PlaceInteractiveOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://decisioning.lexisnexis.com/ws/rules/orderhandler", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string response;
        
        public PlaceInteractiveOrderResponse() {
        }
        
        public PlaceInteractiveOrderResponse(string response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ohwsChannel : AG.Claims.LXNX.AG_CCR.ohws, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ohwsClient : System.ServiceModel.ClientBase<AG.Claims.LXNX.AG_CCR.ohws>, AG.Claims.LXNX.AG_CCR.ohws {
        
        public ohwsClient() {
        }
        
        public ohwsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ohwsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ohwsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ohwsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AG.Claims.LXNX.AG_CCR.PlaceInteractiveOrderResponse AG.Claims.LXNX.AG_CCR.ohws.PlaceInteractiveOrder(AG.Claims.LXNX.AG_CCR.PlaceInteractiveOrder request) {
            return base.Channel.PlaceInteractiveOrder(request);
        }
        
        public string PlaceInteractiveOrder(string request) {
            AG.Claims.LXNX.AG_CCR.PlaceInteractiveOrder inValue = new AG.Claims.LXNX.AG_CCR.PlaceInteractiveOrder();
            inValue.request = request;
            AG.Claims.LXNX.AG_CCR.PlaceInteractiveOrderResponse retVal = ((AG.Claims.LXNX.AG_CCR.ohws)(this)).PlaceInteractiveOrder(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AG.Claims.LXNX.AG_CCR.PlaceInteractiveOrderResponse> AG.Claims.LXNX.AG_CCR.ohws.PlaceInteractiveOrderAsync(AG.Claims.LXNX.AG_CCR.PlaceInteractiveOrder request) {
            return base.Channel.PlaceInteractiveOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<AG.Claims.LXNX.AG_CCR.PlaceInteractiveOrderResponse> PlaceInteractiveOrderAsync(string request) {
            AG.Claims.LXNX.AG_CCR.PlaceInteractiveOrder inValue = new AG.Claims.LXNX.AG_CCR.PlaceInteractiveOrder();
            inValue.request = request;
            return ((AG.Claims.LXNX.AG_CCR.ohws)(this)).PlaceInteractiveOrderAsync(inValue);
        }
    }
}
